name: vcheat
description: Offline Vice City Cheat Overlay
version: 1.0.0+1

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  system_alert_window: 2.0.0
  flutter_accessibility_service: 1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true